### ISSUE TITLE
FR: ability to edit timestamps of existing audio note

### ISSUE THREAD

**Issue by derekvan** [jjmaldonis/obsidian-audio-notes#1]
I'm not sure how possible this is with the new workflow, but I just had an instance where I created the audio note, but then wanted to extend it by a minute. I edited the time stamp, but then there isn't a command to regenerate the audio note (like there was in the previous version). Are these mutually exclusive ways for the plugin to work? If the cursor is in an admonition block when a "generate" command is run, could it know to just regenerate the transcript for that block?

**Comment by derekvan** [comment]
PS: you are on a roll with this! It's so awesome. Hope you add a donation link to the readme.

**Comment by jjmaldonis** [comment]
That's a good point, and I ran into this as well last night. It's fixed now in the newest version, 0.1.4.

There are two commands: `Regenerate Current Audio Note` and `Regenerate All Audio Notes` that you can use to recreate the quotes after changing the timestamps. In both cases, the quotes have to be empty/deleted before a new quote will be created - I kept overwriting quotes on accident, so requiring the note to be empty makes it obvious which note(s) will be recreated.

P.S. Thank you!
