### ISSUE TITLE
FR: Add support for aac audio.

### ISSUE THREAD

**Issue by hugo-blomdahl** [jjmaldonis/obsidian-audio-notes#10]
I store most of my recordings in aac so it would be nice if this extension could support that. m4a files can already be played inside Obsidian by itself. Would it be possible for this extension to work with m4a files? I understand if it is not feasible

**Comment by jjmaldonis** [comment]
I just made a new version that should support m4a files. I'm going to close this issue, but let me know if it isn't working for you.
