### ISSUE TITLE
Transcript file

### ISSUE THREAD

**Issue by abdcef** [jjmaldonis/obsidian-audio-notes#11]
I converted my subtiltles from srt to json. The plugin does not seem to recognize it, and I get an error saying "cannot create audio note at the end of the file".
Is there any specific text required in the json file?

**Comment by jjmaldonis** [comment]
The json requires a `segments` field with a list of `{"start": ..., "end": ..., "text": ...}` objects. So the full JSON format needs to be:

```
{
  "segments": [
    {"start": ..., "end": ..., "text": ...},
    {"start": ..., "end": ..., "text": ...},
    ...
  ]
}
```

However, I just added support for .srt files as transcripts in the latest version (0.2.7). If you update the plugin, you should be able to use your .srt file directly.
