### ISSUE TITLE
[Feature Request] Live update subtitles

### ISSUE THREAD

**Issue by josephdong1000** [jjmaldonis/obsidian-audio-notes#12]
I want to say that I'm a great fan of this plugin and use it especially when I'm rewatching university lectures. It's helpful to listen back to the lecture audio with subtitles on the side.

It would be nice to have the option for subtitles to live update based on where you are in the recording. It would be immensely helpful if there was some option like `liveupdate: true` that would overwrite the subtitles below the recording based on the playback position. This might be a CPU-intensive function, but just being able to see in real-time the words being spoken would improve the QOL of this plugin by a lot!

Cheers!

**Comment by jjmaldonis** [comment]
Hey glad you like the plugin!

This is a cool idea and it ended up being fun to implement.

I haven't documented the feature yet, but you can enable it by setting `liveUpdate: true` (note the capitol `U`) in the code block.

I was able to keep CPU usage low by hooking directly into the audio's HTML element.

Let me know what you think when you give it a try :)

**Comment by josephdong1000** [comment]
This is perfect! The subtitles show up exactly as I imagined, thank you!

A small thing to note for documentation is that I had to add `---` below the audio note description for the subtitles to show. Also, the subtitles don't update automatically when skipping through the audio backward, I had to pause and play for them to update properly. But this is great!
