### ISSUE TITLE
Commands Not Appearing in Command Palette

### ISSUE THREAD

**Issue by julroger2013** [jjmaldonis/obsidian-audio-notes#15]
I installed the audio notes plugin, but the "create new audio note" command doesn't seem to appear in the command palette. I have the .mp3 file I'm aiming for in the vault. Is there something I'm missing about what is needed to create a new audio note?

**Comment by Jestre** [comment]
Same here.  I installed it today but none of the commands that are listed in the docs show up, nor does typing in the commands by hand cause a player to show up.  Wondering if I missed another prerequisite.

**Comment by jjmaldonis** [comment]
Thanks for the report. I'll check it out today and get it fixed.

**Comment by jjmaldonis** [comment]
I just fixed the bug and made a new release. Github's CDN has been slow lately, so Obsidian can't see the new release yet, but it should be visible in Obsidian within a few hours. Last time it took ~ 4 hours, but hopefully it's faster this time.

I'm going to close this issue, but feel free to reopen it if you're still having issues with version 0.6.1.
