### ISSUE TITLE
Deepgram Query

### ISSUE THREAD

**Issue by Jestre** [jjmaldonis/obsidian-audio-notes#16]
Now that 0.6.1 is out and things look like they should work, I grabbed an API key from Deepgram and entered it into the AN config.  I then clicked the microphone icon, the box pops up asking for information (there is an image near the top left which does not display, btw[1]), entered a title, and clicked record.  I read it the Deepgram section of your README and clicked stop.  Waited about 5 minutes but I didn't know how to tell whether the transcription was complete, so I clicked the save audio and transcript button [2].

It does save the recording to the place specified, but it doesn't create a note based on the entered title, nor do I see a transcription.  Over on the Deepgram console, I see two API calls for today, with 1.8 minutes of audio transcribed, but nothing ever shows up in the vault?  Do I need to wait on the dialog box until some transcription complete indicator shows up? 

I also had a json file from whisper, but it didn't appear to have timestamps, so that functionality is not working for me, but I'm assuming if I use your service that flag is set properly to generate timestamps.

Thank you

[1]
```
DG-powered-by-logo-black-red-horizontal-rgb_wqhltl.svg:1          Failed to load resource: the server responded with a status of 404 ()
```

[2]
```
c @ plugin:obsidian-audio-notes:5941
init @ plugin:obsidian-audio-notes:4681
DGQuickAudioNote @ plugin:obsidian-audio-notes:6775
onOpen @ plugin:obsidian-audio-notes:6807
e.open @ app.js:1
eval @ plugin:obsidian-audio-notes:19027
plugin:obsidian-audio-notes:6591 getUserMedia() success, stream created, initializing MediaRecorder
plugin:obsidian-audio-notes:6599 Clamping calculated audio bitrate (2628000bps) to the maximum (128000bps)
eval @ plugin:obsidian-audio-notes:6599
Promise.then (async)
startRecording @ plugin:obsidian-audio-notes:6590
plugin:obsidian-audio-notes:6629 Folder exists. Skipping creation.
plugin:obsidian-audio-notes:6634 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'close')
    at HTMLButtonElement.eval (plugin:obsidian-audio-notes:6634:18)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-audio-notes:147:30)
eval @ plugin:obsidian-audio-notes:6634
fulfilled @ plugin:obsidian-audio-notes:147
Promise.then (async)
step @ plugin:obsidian-audio-notes:160
rejected @ plugin:obsidian-audio-notes:154
Promise.then (async)
step @ plugin:obsidian-audio-notes:160
eval @ plugin:obsidian-audio-notes:162
__awaiter2 @ plugin:obsidian-audio-notes:144
saveTranscription @ plugin:obsidian-audio-notes:6620
```

**Comment by briancbarrow** [comment]
@Jestre I'll take a look at this tomorrow morning and will get back to you

**Comment by briancbarrow** [comment]
@Jestre we made a release last night if you want to update to 0.6.2. Let us know if it still isn't working

**Comment by briancbarrow** [comment]
@Jestre looks like we solved the image problem, but the transcript isn't loading still. I'll let you know here when we release the fix for that

**Comment by Jestre** [comment]
@briancbarrow Okay, just tested again and was going to report that.  Thanks for working on this!

**Comment by briancbarrow** [comment]
Hey @Jestre we got a fix pushed up last night for this. If you get version 0.6.3 it should be working now. Let me know if you have any issues with it still.

**Comment by Jestre** [comment]
@briancbarrow Bingo, worked perfectly on a short recording.  I like the new(?) button text states indicating what is happening.  Many thanks!
