### ISSUE TITLE
[Feature Request] Modify Audio Note Start and End Times from Codeblock Interface

### ISSUE THREAD

**Issue by julroger2013** [jjmaldonis/obsidian-audio-notes#18]
I really like this plugin! Very helpful for processing through podcasts and other audio files. 

I wonder if it would be possible to make it so that fine tailoring of the timespan covered by a particular audio note could be done with sliders or something similar added to the codeblock's interface to designate the start and stop points of a given note: 

![image](https://user-images.githubusercontent.com/94991208/221956334-19637a84-e22e-4cf7-8d60-1ef9fafbbe73.png)

The option to add time at the beginning/end in the plugin's settings is helpful, but it's a rough approximation, and it isn't well-suited for every interesting excerpt, some of which will be longer or shorter than the default. Adjusting the time period covered by an audio note from the player interface would help "fine-tune" the note once the default entry has been created.

**Comment by jjmaldonis** [comment]
Closing this in favor of #19
