### ISSUE TITLE
Remove hard dependency on Admonition plugin

### ISSUE THREAD

**Issue by serpro69** [jjmaldonis/obsidian-audio-notes#2]
Hi and thanks for an interesting plugin for Obsidian!

Here's an issue I noticed right after installing it. Hopefully you can fix this.

Admonition plugin became pretty much obsolete after callouts were added to Obsidian.
While it's perfectly fine to continue using it, it shouldn't be mandatory to have.

The problem I'm seeing here, is that w/o Admonition plugin, playback controls are not visible:
![image](https://user-images.githubusercontent.com/22973227/206551422-f0ba50fb-0201-4fbf-a63a-e0133fa36ab7.png)

With Admonition enabled it works fine:
![image](https://user-images.githubusercontent.com/22973227/206551530-7a007fa9-02cf-475c-8727-a2c1a32612f5.png)

Can this be fixed somehow?

**Comment by jjmaldonis** [comment]
Oh I didn't realize Admonition was basically added to Obsidian, that's cool. I'll work on this in the coming days.

**Comment by jjmaldonis** [comment]
And glad you like the plugin!

**Comment by jjmaldonis** [comment]
Fixed in 8610b4f. It will be updated in the next release.
