### ISSUE TITLE
whisper.cpp as local backed

### ISSUE THREAD

**Issue by homocomputeris** [jjmaldonis/obsidian-audio-notes#32]
Is it possible to configure the plug-in to use (locally built and installed) [whisper.cpp](https://github.com/ggerganov/whisper.cpp) to write transcripts?

The main benefits would be:
- it's completely free
- it can be used offline, e.g. during flights

**Comment by jjmaldonis** [comment]
Hey @homocomputeris, this is a very late reply but unfortunately it's a ton of work to use whisper as a backend. Deepgram is quite inexpensive and they give away $200 worth of free credits when you sign up. It costs ~$0.25 to transcribe 1 hour of audio, so the $200 worth of free credits gives you ~800 hours of free transcription.

Running Whisper for a service like this quite difficult. If you know how to do it, feel free to fork this repo, get whisper running on your own computer, put an API in front of it, and change the URL in this repo to your computer's local API URL. Unfortunately doing this so other people besides yourself can use it is much, much harder.
