### ISSUE TITLE
FR: play / pause & fast forward / rewind commands

### ISSUE THREAD

**Issue by derekvan** [jjmaldonis/obsidian-audio-notes#4]
Would love to have some playback controls as commands so I could give them hotkeys. Play/Pause, skip forward 30s, skip back 10s etc.

**Comment by jjmaldonis** [comment]
We getting fancy now! This was done in commit https://github.com/jjmaldonis/obsidian-audio-notes/commit/0eb0e6cbb0d5bec389adf6ee26ddc57e4d547991 and it's in release 0.1.8.
