### ISSUE TITLE
Support for .srt transcript

### ISSUE THREAD

**Issue by Limezy** [jjmaldonis/obsidian-audio-notes#9]
Hi, thanks for this plugin !
Would it be possible to add support for the standard .srt format ?
The json format you use doesn't seem to be standard, which makes it less future-proof I guess ?

**Comment by jjmaldonis** [comment]
Hey glad you like it. Do you have a link to the .srt format docs? The json is nice because it's what OpenAI Whisper outputs and you can put any additional information in it. I'm guessing the .srt format only supports words and timestamps, but it might work for now.

**Comment by Limezy** [comment]
Hi, thanks for your reply !
The .srt is also a standard Whisper output (in fact, the default one along with .txt. and .vtt if you run `whisper yourfile.mp3`).
You'll find information here : https://en.wikipedia.org/wiki/SubRip
What information does your plugin need, other than a timestamp and associated text ?

**Comment by jjmaldonis** [comment]
Ahh I didn't know that, thanks. Right now it just needs those two. It may not need anything else in the future, but it could make sense to store other info about the audio file, such as its title/name, the current playback position, etc in the "transcript" file. Right now that file only contains the transcript, but since the file is specific to a given audio file / podcast it may make sense to add other info specific to the audio file to the json in the future.

**Comment by Limezy** [comment]
On one hand, I agree. On the other hand, you may also want to expand your plugin from a strict audio -> text workflow to a audio <-> text double sided workflow, where you can for instance have a specific text view (based on a .srt file ?) and you can click on each sentence to launch the audio file at the right moment.
Here is an example, not based on your plugin (yet!). In that case, I guess you could imagine adding other information but still remaining within the .srt format and still be more human readable than a json

https://user-images.githubusercontent.com/24638389/211782286-7de9ccc6-b553-4e62-af08-c8d313ecd6f0.mov

**Comment by jjmaldonis** [comment]
I just added support for .srt files as transcripts in the latest version (0.2.7). If you update the plugin, you should be able to use your .srt file directly in the `transcript: ...` attribute.

**Comment by Limezy** [comment]
Wow that's great, thanks !

**Comment by Bounz** [comment]
> On one hand, I agree. On the other hand, you may also want to expand your plugin from a strict audio -> text workflow to a audio <-> text double sided workflow, where you can for instance have a specific text view (based on a .srt file ?) and you can click on each sentence to launch the audio file at the right moment. Here is an example, not based on your plugin (yet!). In that case, I guess you could imagine adding other information but still remaining within the .srt format and still be more human readable than a json
> 
>  demoTranscript-480.mov

Hi, @Limezy!
How did you achieved that behaviour that clicking on timestamps moves audio player to that moment?
